# Dictionary with old and new station names.
RENAMED_STATIONS = {
                    'Kampin metroasema': "Kamppi (M)",
                    'Sörnäisten metroasema': "Sörnäinen (M)",
                    'Hakaniemen metroasema': "Hakaniemi (M)",
                    'Erottaja': "Erottajan aukio",
                    'Museokatu': "Apollonkatu",
                    'Kauppatori': "Unioninkatu",
                    'Eiran Sairaala': "Kapteeninpuistikko",
                    'Marian Sairaala': "Marian sairaala",
                    "Munkkivuoren ostoskeskus": "Huopalahdentie",
                    "Hylkeenpyytäjänkatu":"Hernesaarenranta",
                    "Kaironkatu":"Verkatehtaanpuisto",
                    "Veturitori":"Diakoniapuisto",
                    "Tiurintie":"Lumivaarantie",
                    "Porkkalankatu":"Itämerentori",
                    "O'Bike Station":"Kaisaniemenpuisto",
                    "Ruomelantie***":"Kuunkatu",
                    "Kalasataman metroasema":"Kalasatama (M)",
                    "Myllypuron metroasema":"Myllypuro (M)",
                    "Herttoniemen metroasema":"Herttoniemi (M)",
                    "Itäkeskuksen metroasema":"Itäkeskus (M)",
                    "Puotilan metroasema":"Puotila (M)",
                    "Cygnauksenkatu":"Cygnaeuksenkatu",
                    "Siilitien metroasema":"Siilitie (M)",
                    "Kulosaaren metroasema":"Kulosaari (M)",
                    "Herttoniemen ranta":"Herttoniemenranta",
                    "Mäntytie":"Paciuksenkatu",
                    "Kalastajantie":"Etuniementie",
                    "Adjutantinkatu":"Postipuun koulu",
                    "Mestarinkatu":"Läkkitori",
                    "Leiritori":"Säteri",
                    "Olarinkatu":"Auringonkatu",
                    "Ulvilanpuisto":"Ulvilantie",
                    "Friisinkalliontie":"Avaruuskatu",
                    "Professorintie":"Laajalahden keskus",
                    "Lahnalahdentie":"Puistokaari",
                    "Niemenmäenkuja":"Huopalahdentie",
                    "Messitytönkatu": "Länsisatamankatu",
                    "Armas Launiksen katu": "Leppävaarankäytävä",
                    "Kauppakartanonkuja": "Petter Wetterin tie"
                    }